/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxpcap_JxpcapAddr */

#ifndef _Included_com_ardikars_jxpcap_JxpcapAddr
#define _Included_com_ardikars_jxpcap_JxpcapAddr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxpcap_JxpcapAddr
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ardikars_jxpcap_JxpcapAddr_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
