/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxpcap_util_JxpcapAddrUtils */

#ifndef _Included_com_ardikars_jxpcap_util_JxpcapAddrUtils
#define _Included_com_ardikars_jxpcap_util_JxpcapAddrUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxpcap_util_JxpcapAddrUtils
 * Method:    nativeGetHwAddr
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ardikars_jxpcap_util_JxpcapAddrUtils_nativeGetHwAddr
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
