/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jxpcap_Captor */

#ifndef _Included_com_jxpcap_Captor
#define _Included_com_jxpcap_Captor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jxpcap_Captor
 * Method:    nativeGetPacket
 * Signature: (JLcom/jxpcap/packet/Packet;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jxpcap_Captor_nativeGetPacket
  (JNIEnv *, jobject, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
