/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jxpcap_Jxpcap */

#ifndef _Included_com_jxpcap_Jxpcap
#define _Included_com_jxpcap_Jxpcap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jxpcap_Jxpcap
 * Method:    nativeOpenLive
 * Signature: (Ljava/lang/String;IIILcom/jxpcap/util/Message;)Lcom/jxpcap/Jxpcap;
 */
JNIEXPORT jobject JNICALL Java_com_jxpcap_Jxpcap_nativeOpenLive
  (JNIEnv *, jclass, jstring, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
