/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jxpcap_Sender */

#ifndef _Included_com_jxpcap_Sender
#define _Included_com_jxpcap_Sender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jxpcap_Sender
 * Method:    nativeSendPacket
 * Signature: (JLjava/nio/ByteBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jxpcap_Sender_nativeSendPacket__JLjava_nio_ByteBuffer_2I
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     com_jxpcap_Sender
 * Method:    nativeSendPacket
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jxpcap_Sender_nativeSendPacket__JII
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
