/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_BpfProgram_Builder */

#ifndef _Included_com_ardikars_jxnet_BpfProgram_Builder
#define _Included_com_ardikars_jxnet_BpfProgram_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
