/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_BpfProgram_BpfCompileMode */

#ifndef _Included_com_ardikars_jxnet_BpfProgram_BpfCompileMode
#define _Included_com_ardikars_jxnet_BpfProgram_BpfCompileMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
