/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jxpcap_util_Devices */

#ifndef _Included_com_jxpcap_util_Devices
#define _Included_com_jxpcap_util_Devices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jxpcap_util_Devices
 * Method:    nativeGetAllDevices
 * Signature: (Ljava/util/List;Lcom/jxpcap/util/Message;)Lcom/jxpcap/util/Devices;
 */
JNIEXPORT jobject JNICALL Java_com_jxpcap_util_Devices_nativeGetAllDevices
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
