/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_util_WLan */

#ifndef _Included_com_ardikars_jxnet_util_WLan
#define _Included_com_ardikars_jxnet_util_WLan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxnet_util_WLan
 * Method:    SetOperationMode
 * Signature: (Lcom/ardikars/jxnet/util/WLan/WLanOperationMode;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ardikars_jxnet_util_WLan_SetOperationMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ardikars_jxnet_util_WLan
 * Method:    GetOperationMode
 * Signature: ()Lcom/ardikars/jxnet/util/WLan/WLanOperationMode;
 */
JNIEXPORT jobject JNICALL Java_com_ardikars_jxnet_util_WLan_GetOperationMode
  (JNIEnv *, jobject);

/*
 * Class:     com_ardikars_jxnet_util_WLan
 * Method:    IsWLan
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ardikars_jxnet_util_WLan_IsWLan
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
