/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_util_AddrUtils */

#ifndef _Included_com_ardikars_jxnet_util_AddrUtils
#define _Included_com_ardikars_jxnet_util_AddrUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxnet_util_AddrUtils
 * Method:    GetMACAddress
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ardikars_jxnet_util_AddrUtils_GetMACAddress
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ardikars_jxnet_util_AddrUtils
 * Method:    GetGatewayAddress
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ardikars_jxnet_util_AddrUtils_GetGatewayAddress
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
