/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_util_WLan_WLanOperationMode */

#ifndef _Included_com_ardikars_jxnet_util_WLan_WLanOperationMode
#define _Included_com_ardikars_jxnet_util_WLan_WLanOperationMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
