/**
 * Copyright (C) 2017  Ardika Rommy Sanjaya
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.ardikars.jxnet.packet.icmp.icmpv6;

import com.ardikars.jxnet.TwoKeyMap;
import com.ardikars.jxnet.packet.icmp.ICMPTypeAndCode;

/**
 * @author Ardika Rommy Sanjaya
 * @since 1.1.5
 */
public class ICMPv6DestinationUnreachable extends ICMPTypeAndCode {

    /**
     * A Destination Unreachable message SHOULD be generated by a router, or
     * by the IPv6 layer in the originating node, in response to a packet
     * that cannot be delivered to its destination address for reasons other
     * than congestion.  (An ICMPv6 message MUST NOT be generated if a
     * packet is dropped due to congestion.)
     *
     * If the reason for the failure to deliver is lack of a matching entry
     * in the forwarding node's routing table, the Code field is set to 0.
     */

    public static final ICMPv6DestinationUnreachable NO_ROUTE_TO_DESTINATION =
            new ICMPv6DestinationUnreachable((byte) 0, "No route to destination");

    public static final ICMPv6DestinationUnreachable COMMUNICATION_WITH_DESTINATION_ADMINIS_TRATIVELY_PROHIBITED =
            new ICMPv6DestinationUnreachable((byte) 1, "Communication with destination administratively prohibited");

    public static final ICMPv6DestinationUnreachable BEYOND_SCOPE_OF_SOURCE_ADDRESS =
            new ICMPv6DestinationUnreachable((byte) 2, "Beyond scope of source address");

    public static final ICMPv6DestinationUnreachable ADDRESS_UNREACHABLE =
            new ICMPv6DestinationUnreachable((byte) 3, "Address unreachable");

    public static final ICMPv6DestinationUnreachable PORT_UNREACHABLE =
            new ICMPv6DestinationUnreachable((byte) 4, "Address unreachable");

    public static final ICMPv6DestinationUnreachable SOURCE_ADDRESS_FAILED =
            new ICMPv6DestinationUnreachable((byte) 5, "Source address failed ingress/egress policy");

    public static final ICMPv6DestinationUnreachable REJECT_ROUTE_TO_DESTINATION =
            new ICMPv6DestinationUnreachable((byte) 6, "Reject route to destination");

    public static final ICMPv6DestinationUnreachable ERROR_IN_SOURCE_ROUTING_HEADER =
            new ICMPv6DestinationUnreachable((byte) 7, "Error in Source Routing Header");

    protected ICMPv6DestinationUnreachable(Byte code, String name) {
        super((byte) 1, code, name);
    }

    public static ICMPv6DestinationUnreachable register(Byte code, String name) {
        TwoKeyMap<Byte, Byte> key = TwoKeyMap.newInstance((byte) 1, code);
        ICMPv6DestinationUnreachable destinationUnreachable =
                new ICMPv6DestinationUnreachable(key.getSecondKey(), name);
        return (ICMPv6DestinationUnreachable) ICMPTypeAndCode.registry.put(key, destinationUnreachable);
    }

    @Override
    public String toString() {
        return super.toString();
    }

    static {
        ICMPTypeAndCode.registry.put(NO_ROUTE_TO_DESTINATION.getKey(), NO_ROUTE_TO_DESTINATION);
        ICMPTypeAndCode.registry.put(COMMUNICATION_WITH_DESTINATION_ADMINIS_TRATIVELY_PROHIBITED.getKey(),
                COMMUNICATION_WITH_DESTINATION_ADMINIS_TRATIVELY_PROHIBITED);
        ICMPTypeAndCode.registry.put(BEYOND_SCOPE_OF_SOURCE_ADDRESS.getKey(), BEYOND_SCOPE_OF_SOURCE_ADDRESS);
        ICMPTypeAndCode.registry.put(ADDRESS_UNREACHABLE.getKey(), ADDRESS_UNREACHABLE);
        ICMPTypeAndCode.registry.put(PORT_UNREACHABLE.getKey(), PORT_UNREACHABLE);
        ICMPTypeAndCode.registry.put(SOURCE_ADDRESS_FAILED.getKey(), SOURCE_ADDRESS_FAILED);
        ICMPTypeAndCode.registry.put(REJECT_ROUTE_TO_DESTINATION.getKey(), REJECT_ROUTE_TO_DESTINATION);
        ICMPTypeAndCode.registry.put(ERROR_IN_SOURCE_ROUTING_HEADER.getKey(), ERROR_IN_SOURCE_ROUTING_HEADER);
    }

}
