/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_BpfProgram */

#ifndef _Included_com_ardikars_jxnet_BpfProgram
#define _Included_com_ardikars_jxnet_BpfProgram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxnet_BpfProgram
 * Method:    initBpfProgram
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ardikars_jxnet_BpfProgram_initBpfProgram
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
