/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_Arp */

#ifndef _Included_com_ardikars_jxnet_Arp
#define _Included_com_ardikars_jxnet_Arp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxnet_Arp
 * Method:    ArpOpen
 * Signature: ()Lcom/ardikars/jxnet/Arp;
 */
JNIEXPORT jobject JNICALL Java_com_ardikars_jxnet_Arp_ArpOpen
  (JNIEnv *, jclass);

/*
 * Class:     com_ardikars_jxnet_Arp
 * Method:    ArpLoop
 * Signature: (Lcom/ardikars/jxnet/Arp;Lcom/ardikars/jxnet/ArpHandler;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_ardikars_jxnet_Arp_ArpLoop
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_ardikars_jxnet_Arp
 * Method:    ArpAdd
 * Signature: (Lcom/ardikars/jxnet/Arp;Lcom/ardikars/jxnet/ArpEntry;)I
 */
JNIEXPORT jint JNICALL Java_com_ardikars_jxnet_Arp_ArpAdd
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_ardikars_jxnet_Arp
 * Method:    ArpDelete
 * Signature: (Lcom/ardikars/jxnet/Arp;Lcom/ardikars/jxnet/ArpEntry;)I
 */
JNIEXPORT jint JNICALL Java_com_ardikars_jxnet_Arp_ArpDelete
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_ardikars_jxnet_Arp
 * Method:    ArpGet
 * Signature: (Lcom/ardikars/jxnet/Arp;Lcom/ardikars/jxnet/ArpEntry;)I
 */
JNIEXPORT jint JNICALL Java_com_ardikars_jxnet_Arp_ArpGet
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_ardikars_jxnet_Arp
 * Method:    ArpClose
 * Signature: (Lcom/ardikars/jxnet/Arp;)Lcom/ardikars/jxnet/Arp;
 */
JNIEXPORT jobject JNICALL Java_com_ardikars_jxnet_Arp_ArpClose
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
