/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_MacAddress */

#ifndef _Included_com_ardikars_jxnet_MacAddress
#define _Included_com_ardikars_jxnet_MacAddress
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ardikars_jxnet_MacAddress_MAC_ADDRESS_LENGTH
#define com_ardikars_jxnet_MacAddress_MAC_ADDRESS_LENGTH 6L
/*
 * Class:     com_ardikars_jxnet_MacAddress
 * Method:    fromNicName
 * Signature: (Ljava/lang/String;)Lcom/ardikars/jxnet/MacAddress;
 */
JNIEXPORT jobject JNICALL Java_com_ardikars_jxnet_MacAddress_fromNicName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
