/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ardikars_jxnet_util_Preconditions */

#ifndef _Included_com_ardikars_jxnet_util_Preconditions
#define _Included_com_ardikars_jxnet_util_Preconditions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ardikars_jxnet_util_Preconditions
 * Method:    CheckArgument
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ardikars_jxnet_util_Preconditions_CheckArgument__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ardikars_jxnet_util_Preconditions
 * Method:    CheckArgument
 * Signature: (ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ardikars_jxnet_util_Preconditions_CheckArgument__ZLjava_lang_String_2
  (JNIEnv *, jclass, jboolean, jstring);

/*
 * Class:     com_ardikars_jxnet_util_Preconditions
 * Method:    CheckState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_ardikars_jxnet_util_Preconditions_CheckState__Z
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ardikars_jxnet_util_Preconditions
 * Method:    CheckState
 * Signature: (ZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ardikars_jxnet_util_Preconditions_CheckState__ZLjava_lang_String_2
  (JNIEnv *, jclass, jboolean, jstring);

/*
 * Class:     com_ardikars_jxnet_util_Preconditions
 * Method:    CheckNotNull
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_ardikars_jxnet_util_Preconditions_CheckNotNull__Ljava_lang_Object_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_ardikars_jxnet_util_Preconditions
 * Method:    CheckNotNull
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_ardikars_jxnet_util_Preconditions_CheckNotNull__Ljava_lang_Object_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
